# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dates', models.CharField(blank=True, max_length=200, null=True)),
                ('information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('vdgs', models.CharField(blank=True, max_length=20, null=True)),
                ('parts', models.IntegerField()),
                ('instrumentation', models.CharField(blank=True, max_length=200, null=True)),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.Person')),
                ('files', models.ManyToManyField(to='scores.File')),
                ('instrument', models.ManyToManyField(blank=True, null=True, to='scores.Instrument')),
                ('lyricist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='composed_piece', to='scores.Person')),
            ],
        ),
    ]
