# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_instrument_person_piece'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='shortname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
