# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_piece_shortname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='piece',
            name='instrumentation',
        ),
        migrations.AddField(
            model_name='piece',
            name='instrumentation',
            field=models.ManyToManyField(to='scores.Instrumentation'),
        ),
    ]
