# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20160201_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='shortinst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
