# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_piece_shortinst'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['surname']},
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='names',
        ),
        migrations.AddField(
            model_name='person',
            name='surname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='piece',
            name='files',
            field=models.ManyToManyField(blank=True, to='scores.File'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='instrument',
            field=models.ManyToManyField(blank=True, to='scores.Instrument'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='instrumentation',
            field=models.ManyToManyField(blank=True, to='scores.Instrumentation'),
        ),
    ]
