# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-06 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_piece_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensing',
            name='short_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
